version: '3'
services:
    db:
        image: quay.io/azavea/postgis:3-postgres12.2-slim
        ports:
            - "8765:5432"
        restart: always
        volumes:
            - /var/lib/postgresql/data/
        env_file: scripts/docker/.env
    rainfall_db:
        image: quay.io/azavea/postgis:3-postgres12.2-slim
        ports:
            - "8766:5432"
        restart: always
        volumes:
            - /var/lib/postgresql/data/
        env_file: scripts/docker/.env
    db-init:
        build:
            context: .
            dockerfile: scripts/docker/db-init/Dockerfile
        depends_on:
            - db
        env_file: scripts/docker/.env
    rainfall-db-init:
        build:
            context: .
            dockerfile: scripts/docker/rainfall-db-init/Dockerfile
        depends_on:
            - rainfall_db
        env_file: scripts/docker/.env
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        env_file: scripts/docker/.env
    app:
        build:
            context: .
            dockerfile: scripts/docker/trwwapi/Dockerfile
        command: python3 manage.py runserver 0.0.0.0:7000
        depends_on:
            - db
            - rainfall_db
            - redis
        ports:
            - "7000:7000"
        volumes:
            - .:/code
        env_file: scripts/docker/.env
        environment:
            DEBUG: 1
        mem_limit: 1gb
    worker:
        build:
            context: .
            dockerfile: scripts/docker/trwwapi/Dockerfile
        command: python3 manage.py rqworker default
        depends_on:
            - app
        environment:
            DEBUG: 1
        volumes:
            - .:/code
        env_file: scripts/docker/.env
        mem_limit: 512m
