version: '3'
services:
    db:
        image: quay.io/azavea/postgis:3-postgres12.2-slim
        ports: 
            - "5432:5432"
        restart: always
        volumes:
            - /var/lib/postgresql/data/
        env_file: .env.docker
    rainfall_db:
        image: quay.io/azavea/postgis:3-postgres12.2-slim
        ports: 
            - "5435:5432"
        restart: always
        volumes:
            - /var/lib/postgresql/data/
        env_file: .env.docker
    db-init:
        build:
            context: .
            dockerfile: docker/db-init/Dockerfile
        depends_on:
            - db
        env_file: .env.docker
    rainfall-db-init:
        build:
            context: .
            dockerfile: docker/rainfall-db-init/Dockerfile
        depends_on:
            - rainfall_db
        env_file: .env.docker
    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        env_file: .env.docker             
    app:
        build: 
            context: .
            dockerfile: docker/trwwapi/Dockerfile
        command: python3 manage.py runserver 0.0.0.0:7000
        depends_on:
            - db
            - rainfall_db
            - redis
        ports:
            - "7000:7000"
        volumes:
          - .:/code
        env_file: .env.docker
    worker:
        build:
            context: .
            dockerfile: docker/trwwapi/Dockerfile
        command: python3 manage.py rqworker default
        depends_on:
            - app        
        environment:
            DEBUG: 1
        volumes:
            - .:/code
        env_file: .env.docker
