# Generated by Django 4.1 on 2022-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0002_garr5record_garrrecord_gaugerecord_rtrg5record_rtrgrecord_rtrrrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GarrObservation',
        ),
        migrations.DeleteModel(
            name='GaugeObservation',
        ),
        migrations.DeleteModel(
            name='RtrgObservation',
        ),
        migrations.DeleteModel(
            name='RtrrObservation',
        ),
        migrations.AlterModelOptions(
            name='garr5record',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='garrrecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gaugerecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rtrg5record',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rtrgrecord',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rtrrrecord',
            options={'managed': False},
        ),
        migrations.RemoveField(
            model_name='rainfallreport',
            name='events',
        ),
        migrations.AddField(
            model_name='gauge',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='web_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rainfallevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rainfallreport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
