# Generated by Django 4.1 on 2022-08-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall', '0003_delete_garrobservation_delete_gaugeobservation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gauge',
            options={'ordering': ['ext_id']},
        ),
    ]
