# Generated by Django 4.1 on 2022-08-17 13:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import trwwapi.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('rainfall', '0004_alter_gauge_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, help_text='Name of the resource', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='slug is used by selectors for querying by name', max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the resource')),
                ('datetime', models.DateTimeField(blank=True, verbose_name='Resource publication Date/Time')),
                ('href', models.CharField(blank=True, help_text='Resource location. May be a URL or cloud resource (e.g., S3://', max_length=2048)),
                ('meta', models.JSONField(blank=True, default=trwwapi.common.models.Resource.data_default, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(help_text='A human readable title describing the Collection.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed multi-line description to fully explain the Collection.')),
                ('resources', models.ManyToManyField(blank=True, to='rainfall.resource')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('label', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('meta', models.JSONField(blank=True, default=trwwapi.common.models.Boundary.data_default, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rainfall.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
