# Generated by Django 4.1 on 2022-08-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainways', '0003_auto_20210413_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
