# Generated by Django 4.1 on 2022-08-16 15:42

from django.db import migrations, models
import trwwapi.rainways.models


class Migration(migrations.Migration):

    dependencies = [
        ('rainways', '0004_alter_collection_id_alter_resource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='meta',
            field=models.JSONField(blank=True, default=trwwapi.rainways.models.Resource.data_default, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='resources',
            field=models.ManyToManyField(blank=True, to='rainways.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(blank=True, help_text='Name of the resource', max_length=255),
        ),
    ]
