# Generated by Django 4.1 on 2022-08-16 17:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import trwwapi.rainways.models


class Migration(migrations.Migration):

    dependencies = [
        ('rainways', '0005_resource_meta_resource_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(blank=True, default=trwwapi.rainways.models.Resource.slug_default, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('uid', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('label', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('meta', models.JSONField(blank=True, default=trwwapi.rainways.models.Boundary.data_default, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rainways.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
