# Generated by Django 4.1 on 2022-08-16 20:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainways', '0006_alter_resource_slug_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
